#!/bin/bash

function action(){
    for file in `ls $1` 
    do
        if [ -d $1"/"$file ] 
        then
            action $1"/"$file
        elif [ "${file#*.}"x = "md"x ]
        then
            # 方便用typora阅读
            sed -i 's/{{<\s*katex\s*>}}/$$/g; s/{{<\s*katex\s*display\s*>}}/$$/g; s/{{<\s*\/katex\s*>}}/$$/g; s/!\[\s*\](\.\.\/\.\.\/images\//![](..\/images\//g; '  $1"/"$file
        fi
    done
} 

action ./content



