#!/bin/bash

path=`pwd`
if [ "${path##*/}"x = "notes"x ] 
then
    # 生成待发布的数据
    ./forgitee
    
    # 数据备份
    rm -rd ../public
    mv public ../
    cp .gitignore ../public/
    cp publish ../

    # 切换到发布分支
    git add .
    git commit -m "忘提交则补提交"
    git checkout gh-pages

    # # 重新执行
    cd ..

    if [ "$1"x = "force"x ] 
    then
        ./publish force
    else
        ./publish
    fi
elif  [ -d "./notes" ]    
then
    cd notes

    if [ "$1"x = "force"x ] 
    then
        # 清空库
	git checkout --orphan gh-pages-bak
	git branch -D gh-pages
	rm -rf *
	touch commit
	git add .
	git commit -m "commit"
	git branch -m gh-pages
    fi

    rm -rf *

    # 数据提交
    cp -r  ../public/*  ./
    git add .
    git commit -m "发布"

    # 发布
    if [ "$1"x = "force"x ] 
    then
        git push gitee gh-pages --force
        git push github gh-pages --force
    else
        git push gitee gh-pages
        git push github gh-pages
    fi

    # 复原
    git checkout master
    rm -rf  ../public
    rm ../publish
else
    echo "此脚本只能在特定目录（notes目录或其父目录）中执行"
fi

